CREATE DATABASE apirestmysql;

USE apirestmysql;

CREATE TABLE IF NOT EXISTS expenses (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
    descripcion VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARACTER SET=utf8;

DESCRIBE expenses;